### ISSUE TITLE
Error after trying to run command

### ISSUE THREAD

**Issue by synth-tenor** [K4rakara/freshfetch#17]
I have installed the freshfetch-bin aur package, and after trying to run it i get the error: `Error.
A Lua error occurred. Details:
syntax error: [string "?"]:134: ')' expected (to close '(' at line 131) near ':'` I'm not really sure what is causing this, maybe I did something wrong.

**Comment by K4rakara** [comment]
Thats odd-- I'll take a look at.

You didn't add a custom Lua config in `~/.config/freshfetch/{art,layout,info}.lua`, did you? If you did, could you share it?

**Comment by synth-tenor** [comment]
I have not added any configs or anything

**Comment by K4rakara** [comment]
Can you try using `freshfetch-git`?

**Comment by synth-tenor** [comment]
Sorry i took so long to respond! It seems that this problem has become something else now: I dont get a lua error, but now if i run the command it takes a couple minutes to actually display anything. I'm not sure if it may be a problem with my distro, im using EndeavourOS.

**Comment by K4rakara** [comment]
Oh god, a few minutes? Would it be possible for me to make a branch that logs when each diagnostic finishes, so that I can get a better idea at what might be slowing it down?

If not, my first question is: Are you using low end hardware?
Secondly, are you using multiple package managers?

**Comment by synth-tenor** [comment]
To answer your questions, i am using fairy capable hardware (ryzen 5 2600, 16gb ram, rx 550), and at the time of testing i was only running pacman and yay. I would love to do some more testing, but i've since moved on from endeavourOs. I'd suggest maybe trying the aur packages in vm's with other arch based distros.

**Comment by K4rakara** [comment]
The thing is, I use arch, so I can't imagine it being an issue with base arch itself. However, it might be an issue with EndeavorOS, so I will give that a try.

**Comment by xpyxel** [comment]
I have the lua error on this myself, running on Oracle Linux 8 within WSL. I downloaded the last release from the releases and ran it, no configs or anything.

**Comment by ThisNekoGuy** [comment]
I also have this error after just running the command with ```freshfetch-bin``` in EndeavourOS.

_System Info:_
- Ryzen 3700X
- 16GBs DDR4 3600MHz RAM
- 2080 Ti

**Comment by K4rakara** [comment]
Should be fixed in 0.2.0
