### ISSUE TITLE
--help outputs nothing

### ISSUE THREAD

**Issue by StudioChew** [K4rakara/freshfetch#2]
I ran the command `freshfetch --help`, but the output was completely blank.

**Comment by K4rakara** [comment]
Damn it-- I knew I was forgetting something. I'll be adding a help menu in version `0.1.1`.

**Comment by K4rakara** [comment]
Version 0.1.1 is released, and with it, a help menu is added.

**Comment by K4rakara** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add help option](https://trello.com/c/IAXOsIgh/8-add-help-option)
