### ISSUE TITLE
Compiling falied

### ISSUE THREAD

**Issue by AbhinavAchha** [K4rakara/freshfetch#24]
I am facing issues while compiling 

[log.log](https://github.com/K4rakara/freshfetch/files/6590112/log.log)

My system:
Os- Fedora 34
Cargo version- cargo 1.52.0 (69767412a 2021-04-21)
Rustc version-rustc 1.54.0-dev

**Comment by Crstian19** [comment]
You have to install `rustup` and then `rustup toolchain install nightly` before install it, worked for me.

**Comment by AbhinavAchha** [comment]
i tried installing it by using nightly but still the build failed.

**Comment by K4rakara** [comment]
> i tried installing it by using nightly but still the build failed.

The issue you are facing is related to the cmd-rs dependency. I'm gonna work on removing that dependency, as it causes many issues.
