### ISSUE TITLE
How do I customize freshfetch?

### ISSUE THREAD

**Issue by amarakon** [K4rakara/freshfetch#26]
How do I customize freshfetch? Where is the configuration file? I want my freshfetch to look like this example:
https://raw.githubusercontent.com/K4rakara/freshfetch/master/readme/config-2.png

**Comment by K4rakara** [comment]
The configuration files are in ` ~/.config/freshfetch/art.lua`, `~/.config/freshfetch/info.lua`, and `~/.config/freshfetch/layout.lua`. 

The config in that image is in [`/examples/personal`](https://github.com/K4rakara/freshfetch/tree/master/examples/personal)
