### ISSUE TITLE
How do I Print the Bold Version of the Gentoo Logo?

### ISSUE THREAD

**Issue by amarakon** [K4rakara/freshfetch#27]
My operating system is Gentoo, and it shows the proper logo, but it's not Bold. I would like the logo to be bold, but whenever I try to change the art.lua it gives me errors when running freshfetch. What should my art.lua contain in order to print the same logo, but the bold version?

**Comment by K4rakara** [comment]
To do that, you would actually use `layout.lua`:
```lua
print(""..save())

print("  \x1b[1m"..string.gsub(string.gsub(art, "\n", "\n  "), "\x1b[0m", "\x1b[0m\x1b[1m").."\x1b[0m")

print(""..up(artHeight))

print(""
	..right(artWidth + 4)
	..string.gsub(info,
		"\n",
		"\n"..right(artWidth + 4)))

print(""..restore())

if infoHeight > artHeight then
	print(""..down(infoHeight))
else
	print(""..down(artHeight))
end
```

This is basically just `examples/default/layout.lua`, but it replaces all ANSI reset characters (`\x1b[0m`) with an ANSI reset character and a ANSI bold character (`\x1b[1m`)

**Comment by amarakon** [comment]
Ok, thanks.
