### ISSUE TITLE
What is the icon font used in the personal example?

### ISSUE THREAD

**Issue by amarakon** [K4rakara/freshfetch#28]
In this example: https://raw.githubusercontent.com/K4rakara/freshfetch/master/readme/config-2.png

You have some nice custom icons. I use fontawesome, but there are icons in there that fontawesome doesn't have. For example, the GPU icon. What is the font used for the icons in that example?

**Comment by K4rakara** [comment]
This is using the Material Design Icons webfont

**Comment by amarakon** [comment]
Also do you know what is the name of the icon you used for the kernel?

**Comment by amarakon** [comment]
Also do you know what is the name of the icon you used for the kernel?

**Comment by K4rakara** [comment]
> Also do you know what is the name of the icon you used for the kernel?

U+F033D / mdi-linux

**Comment by amarakon** [comment]
Thanks, I for the icon for the kernel, do you know the icon name for the gpu?
