### ISSUE TITLE
Cannot start program, OS error code 2

### ISSUE THREAD

**Issue by BachoSeven** [K4rakara/freshfetch#3]
Not the same error as #1; AUR build on ArchLinux x86_64; output of `RUST_BACKTRACE=full freshfetch`:

``` rust
$ RUST_BACKTRACE=full freshfetch
thread 'main' panicked at 'error reading file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/info/gpu.rs:40:38
stack backtrace:
   0:     0x561f6bdccda5 - <unknown>
   1:     0x561f6bdf335c - <unknown>
   2:     0x561f6bdc93a2 - <unknown>
   3:     0x561f6bdcf440 - <unknown>
   4:     0x561f6bdcf18c - <unknown>
   5:     0x561f6bdcfa83 - <unknown>
   6:     0x561f6bdcf67b - <unknown>
   7:     0x561f6bdf1d01 - <unknown>
   8:     0x561f6bdf1b23 - <unknown>
   9:     0x561f6bc7b602 - <unknown>
  10:     0x561f6bc84973 - <unknown>
  11:     0x561f6bc91af0 - <unknown>
  12:     0x561f6bca258a - <unknown>
  13:     0x561f6bc8def3 - <unknown>
  14:     0x561f6bdcff23 - <unknown>
  15:     0x561f6bca3552 - <unknown>
  16:     0x7fb4e843c152 - __libc_start_main
  17:     0x561f6bc720ee - <unknown>
```

**Comment by K4rakara** [comment]
Its close to issue #1, but its not identical. This one seems to be an issue with gpu.rs rather than cpu.rs. I'll look into the issue, thanks for reporting.

**Comment by K4rakara** [comment]
@BachoSeven now that I'm looking at the code, it looks like that line is when the program calls the program `lspci`. Do you have that installed on your system?

**Comment by BachoSeven** [comment]
Yes, as a part of `pciutils`.

**Comment by K4rakara** [comment]
@BachoSeven  Could you try this with the development version?
If you're using the AUR version:
```bash
cd src/freshfetch/
git pull
git checkout v0.1.2
cd ../..
makepkg
```
If you're using the raw repo:
```bash
git pull
git checkout v0.1.2
cargo build --release -vv
```

**Comment by BachoSeven** [comment]
Yes, that fixes the issue!

**Comment by K4rakara** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GPU detection](https://trello.com/c/tMzuOZHD/2-gpu-detection)

**Comment by K4rakara** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Motherboard name detection](https://trello.com/c/n0MTvgVj/4-motherboard-name-detection)
