### ISSUE TITLE
Wrong uptime shown.

### ISSUE THREAD

**Issue by ras-drive** [K4rakara/freshfetch#32]
When I run the uptime command my uptime is shown as 49 days but on freshfetch it says 18 days.

**Comment by K4rakara** [comment]
I'm really unsure why this would happen, unless `/proc/uptime` is treated differently on Solus. I'll try to replace this method of determining the system time with posix calls, that should probably fix it.

**Comment by liyiheng** [comment]
fn day(&self)-> u32
> Returns the day of month starting from 1.

fn ordinal0(&self) -> u32
> Returns the day of year starting from 0.

Current implement based on  `day()-1`, if uptime greater than 31 days, there would by an incorrect result.
Maybe `std::time::Duration` is better.
